version: '3.8'

services:
  service:
    container_name: users_service
    build:
      context: .
      dockerfile: build/docker/service/Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      .env